spring:
  redis:
    host: 192.168.64.100
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0

baidu:
#  apikey: tT4qxuFc5JKSVgePkmyHunok
#  secretkey: gHDLacrqfKW6vezM6bM6XE1RURqELO3I
  apikey: gTDm4Ul3vlNIxeFROHLKPNIF
  secretkey: vLmRM8fOUbUyVpdKmBw1Jl3HGACt17cK
